protected/modules/saw/controllers/CriteriaController.php
<?php

class CriteriaController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    //public $layout = 'main';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'create', 'update', 'admin', 'delete'),
                'users' => array('*'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new SawCriteria;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['SawCriteria'])) {
            $model->attributes = $_POST['SawCriteria'];
            $model->type = $_POST['SawCriteria']['type'][0];
            if ($model->save())
                $this->redirect(array('admin'));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['SawCriteria'])) {
            $model->attributes = $_POST['SawCriteria'];
            $model->type = $_POST['SawCriteria']['type'][0];
            if ($model->save())
                $this->redirect(array('admin'));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('SawCriteria');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new SawCriteria('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['SawCriteria']))
            $model->attributes = $_GET['SawCriteria'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return SawCriteria the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = SawCriteria::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param SawCriteria $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'saw-criteria-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/modules/saw/controllers/PersonController.php
<?php

class PersonController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    //public $layout = 'main';

    public function actionValue($id) {
        $person = Person::model()->findByPk($id);
        $x = new CDbCriteria();
        $x->order = 'no_urut';
        $criteria = SawCriteria::model()->findAll($x);
        $data = $this->getValue($id);
        if (isset($_POST['Value'])) {
            SawValue::model()->deleteAllByAttributes(array('person_id' => $id));
            foreach ($criteria as $row) {
                if (isset($_POST['Value'][$row->criteria_id])) {
                    $insert = new SawValue();
                    $insert->person_id = $id;
                    $insert->criteria_id = $row->criteria_id;
                    $insert->value = $_POST['Value'][$row->criteria_id];
                    $insert->save(false);
                }
            }
            $this->redirect(array('admin'));
        }
        $this->render('value', array(
            'person' => $person,
            'data' => $data,
            'criteria' => $criteria
        ));
    }

    public function getValue($id) {
        $data = array();
        $value = SawValue::model()->findAllByAttributes(array('person_id' => $id));
        if ($value !== NULL)
            foreach ($value as $row) {
                $data[$row->criteria_id] = $row->value;
            }
        return $data;
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Person;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Person'])) {
            $model->attributes = $_POST['Person'];
            if ($model->save())
                $this->redirect(array('admin'));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Person'])) {
            $model->attributes = $_POST['Person'];
            if ($model->save())
                $this->redirect(array('admin'));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Person');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Person('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Person']))
            $model->attributes = $_GET['Person'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Person the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Person::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Person $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'person-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/modules/saw/views/layouts/main.php
<!DOCTYPE html>
<html class="no-js">

    <head>
        <title><?php echo Yii::app()->name; ?></title>
        <!-- Bootstrap -->
        <link href="<?php echo Yii::app()->theme->baseUrl; ?>/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="<?php echo Yii::app()->theme->baseUrl; ?>/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
        <link href="<?php echo Yii::app()->theme->baseUrl; ?>/vendors/easypiechart/jquery.easy-pie-chart.css" rel="stylesheet" media="screen">
        <link href="<?php echo Yii::app()->theme->baseUrl; ?>/assets/styles.css" rel="stylesheet" media="screen">       
        <link href="<?php echo Yii::app()->theme->baseUrl; ?>/assets/sticky-footer-navbar.css" rel="stylesheet">
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link rel="icon" href="<?php echo Yii::app()->theme->baseUrl; ?>/images/favicon.ico" type="image/x-icon" />
        <script src="<?php echo Yii::app()->theme->baseUrl; ?>/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>        
    </head>

    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo Yii::app()->homeUrl; ?>"><?php echo Yii::app()->name; ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="">
                                <a href="#"> <i class="icon-user"></i> <span style="color: blue; font-weight: bold;">Nur Ichsan</span> (372281) </a>                                
                            </li>
                        </ul>
                        <ul class="nav">
                            <li class="">
                                <a href="<?php echo Yii::app()->homeUrl; ?>"><i class="icon-home"></i> Home</a>
                            </li>
                            <li class="">
                                <a href="<?php echo Yii::app()->createUrl($this->module->id . '/person/admin'); ?>"><i class="icon-user"></i> Person</a>                                
                            </li>
                            <li class="">
                                <a href="<?php echo Yii::app()->createUrl($this->module->id . '/criteria/admin'); ?>"><i class="icon-bookmark"></i> Criteria</a>                                
                            </li>                            
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row-fluid">                

                <div class="span12" id="content">                                                                                
                    <?php echo $content; ?>             
                </div>
            </div>                        
        </div>
        <footer class="footer">                                        
            <div class="navbar navbar-fixed-bottom">                
                <div class="navbar-inner">
                    <div class="container-fluid">     
                        <div class="nav-collapse collapse">
                            <ul class="nav pull-left">
                                <li class="">
                                    <a href="#"> <i class="icon-bullhorn"></i> Dikembangkan sebagai tugas kuliah Sistem Pendukung Keputusan. </a>                                
                                </li>
                            </ul>
                        </div>                        
                    </div>                
                </div>
            </div>
        </footer>
        <!--/.fluid-container-->
        <?php
        $cs = Yii::app()->clientScript;
        $cs->registerCoreScript('jquery');
        ?>        
        <script src="<?php echo Yii::app()->theme->baseUrl; ?>/bootstrap/js/bootstrap.min.js"></script>
        <script src="<?php echo Yii::app()->theme->baseUrl; ?>/vendors/easypiechart/jquery.easy-pie-chart.js"></script>        
        <script type="text/javascript" src="<?php echo Yii::app()->theme->baseUrl; ?>/vendors/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="<?php echo Yii::app()->theme->baseUrl; ?>/assets/form-validation.js"></script>
        <script src="<?php echo Yii::app()->theme->baseUrl; ?>/assets/scripts.js"></script>
        <script>        
            jQuery(document).ready(function() {   
                FormValidation.init();
            });
        </script>
    </script>
</body>

</html>